import { bigint, boolean, date, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const attendanceStatus = pgEnum("attendance_status", ["present", "absent", "leave", "holiday", "incomplete"]);
export const componentKind = pgEnum("component_kind", ["earning", "deduction", "net"]);
export const periodStatus = pgEnum("period_status", ["draft", "processing", "locked"]);
const tracked = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const employees = pgTable("employees", { id: uuid("id").defaultRandom().primaryKey(), personnelCode: text("personnel_code").notNull(), fullName: text("full_name").notNull(), employmentStatus: text("employment_status").default("active").notNull(), startDate: date("start_date").notNull(), endDate: date("end_date"), baseSalary: numeric("base_salary", { precision: 18, scale: 2 }).default("0").notNull(), duties: text("duties").default("").notNull(), customValues: jsonb("custom_values").default({}).notNull(), ...tracked }, (t) => [uniqueIndex("employees_personnel_code_uq").on(t.personnelCode)]);
export const workSchedules = pgTable("work_schedules", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), startMinute: integer("start_minute").notNull(), endMinute: integer("end_minute").notNull(), breakMinutes: integer("break_minutes").default(0).notNull(), workDays: jsonb("work_days").default([1,2,3,4,5]).notNull(), isDefault: boolean("is_default").default(false).notNull(), ...tracked });
export const holidays = pgTable("holidays", { id: uuid("id").defaultRandom().primaryKey(), holidayDate: date("holiday_date").notNull(), title: text("title").notNull(), ...tracked }, (t) => [uniqueIndex("holidays_date_uq").on(t.holidayDate)]);
export const scheduleOverrides = pgTable("schedule_overrides", { id: uuid("id").defaultRandom().primaryKey(), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "cascade" }), workDate: date("work_date").notNull(), scheduleId: uuid("schedule_id").references(() => workSchedules.id), isHoliday: boolean("is_holiday").default(false).notNull(), ...tracked });
export const leaveTypes = pgTable("leave_types", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), unit: text("unit").default("hourly").notNull(), isPaid: boolean("is_paid").default(true).notNull(), ...tracked });
export const attendanceEntries = pgTable("attendance_entries", { id: uuid("id").defaultRandom().primaryKey(), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "cascade" }).notNull(), workDate: date("work_date").notNull(), checkInMinute: integer("check_in_minute"), checkOutMinute: integer("check_out_minute"), breakMinutes: integer("break_minutes").default(0).notNull(), leaveTypeId: uuid("leave_type_id").references(() => leaveTypes.id), leaveMinutes: integer("leave_minutes").default(0).notNull(), actualMinutes: integer("actual_minutes").default(0).notNull(), requiredMinutes: integer("required_minutes").default(0).notNull(), delayMinutes: integer("delay_minutes").default(0).notNull(), earlyLeaveMinutes: integer("early_leave_minutes").default(0).notNull(), deficitMinutes: integer("deficit_minutes").default(0).notNull(), overtimeMinutes: integer("overtime_minutes").default(0).notNull(), computedStatus: attendanceStatus("computed_status").notNull(), overrideStatus: attendanceStatus("override_status"), overrideReason: text("override_reason"), notes: text("notes"), ...tracked }, (t) => [uniqueIndex("attendance_employee_date_uq").on(t.employeeId, t.workDate)]);
export const formulaComponents = pgTable("formula_components", { id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull(), name: text("name").notNull(), kind: componentKind("kind").notNull(), activeVersionId: uuid("active_version_id"), ...tracked }, (t) => [uniqueIndex("formula_component_code_uq").on(t.code)]);
export const formulaVersions = pgTable("formula_versions", { id: uuid("id").defaultRandom().primaryKey(), componentId: uuid("component_id").references(() => formulaComponents.id, { onDelete: "cascade" }).notNull(), version: integer("version").notNull(), expression: jsonb("expression").notNull(), expressionText: text("expression_text").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const payrollPeriods = pgTable("payroll_periods", { id: uuid("id").defaultRandom().primaryKey(), year: integer("year").notNull(), month: integer("month").notNull(), status: periodStatus("status").default("draft").notNull(), lockedAt: timestamp("locked_at", { withTimezone: true }), snapshot: jsonb("snapshot"), ...tracked }, (t) => [uniqueIndex("period_year_month_uq").on(t.year,t.month)]);
export const payrollResults = pgTable("payroll_results", { id: uuid("id").defaultRandom().primaryKey(), periodId: uuid("period_id").references(() => payrollPeriods.id, { onDelete: "cascade" }).notNull(), employeeId: uuid("employee_id").references(() => employees.id).notNull(), inputs: jsonb("inputs").notNull(), componentResults: jsonb("component_results").notNull(), earnings: numeric("earnings", { precision:18, scale:2 }).notNull(), deductions: numeric("deductions", { precision:18, scale:2 }).notNull(), netPay: numeric("net_pay", { precision:18, scale:2 }).notNull(), calculatedAt: timestamp("calculated_at", { withTimezone:true }).defaultNow().notNull() }, (t) => [uniqueIndex("result_period_employee_uq").on(t.periodId,t.employeeId)]);
export const importBatches = pgTable("import_batches", { id: uuid("id").defaultRandom().primaryKey(), fileName: text("file_name").notNull(), status: text("status").notNull(), totalRows: integer("total_rows").default(0).notNull(), acceptedRows: integer("accepted_rows").default(0).notNull(), rejectedRows: integer("rejected_rows").default(0).notNull(), errors: jsonb("errors").default([]).notNull(), createdAt: timestamp("created_at", { withTimezone:true }).defaultNow().notNull() });
export const auditLogs = pgTable("audit_logs", { id: bigint("id", { mode:"number" }).primaryKey().generatedAlwaysAsIdentity(), occurredAt: timestamp("occurred_at", { withTimezone:true }).defaultNow().notNull(), actorId: text("actor_id").default("local-admin").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), beforeValue: jsonb("before_value"), afterValue: jsonb("after_value"), reason: text("reason"), sessionId: text("session_id"), batchId: uuid("batch_id") });
